version: '3.4'

services:
  bicyclecompany.bll:
    image: ${DOCKER_REGISTRY-}bicyclecompanybll
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5001:443"
    depends_on: 
        - db
    environment:
        - TZ=Europe/Moscow
  
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    volumes:
        - db-storage:/var/opt/mssql/data
    environment:
        SA_PASSWORD: "My_password_123"
        ACCEPT_EULA: "Y"

volumes:
    db-storage: